---

- name: Firewalls Palo Alto Compliance log
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:

    - name: COMPLIANCE LOG - SET EVENT VAR
      set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: COMPLIANCE TAG - POLICY MANUAL CHANGE (adminmanual)
      block:

        - name: COMPLIANCE LOG - GET INFO ON ADDED RULES (adminmanual)
          paloaltonetworks.panos.panos_security_rule:
            provider: '{{ panos_provider }}'
            rule_name: "{{ payload.path | regex_search('.*rulebase security rules  (.*)','\\1') | first}}"
            state: gathered
          register: _rules_result
          when: payload.admin == "adminmanual"

        - name: COMPLIANCE LOG - SET LOGS TO log_start AND log_end (adminmanual)
          paloaltonetworks.panos.panos_security_rule:
            provider: "{{ panos_provider }}"
            rule_name: "{{ _rules_result.gathered.rule_name }}"
            log_start: true
            log_end: true
            state: replaced

      when: payload.admin == "adminmanual"

    - name: COMPLIANCE LOG - POLICY ANSIBLE CHANGE (admin)
      block:

        - name: COMPLIANCE LOG - GET INFO ON ADDED RULES (admin)
          paloaltonetworks.panos.panos_security_rule:
            provider: '{{ panos_provider }}'
            rule_name: "{{ payload.after_change_detail.split(' ')[2] }}"
            state: gathered
          register: _rules_result

        - name: COMPLIANCE LOG - SET LOGS TO log_start AND log_end (admin)
          paloaltonetworks.panos.panos_security_rule:
            provider: "{{ panos_provider }}"
            rule_name: "{{ _rules_result.gathered.rule_name }}"
            log_start: true
            log_end: true
            state: replaced

      when: payload.admin == "admin"

    - name: COMPLIANCE LOG - COMMIT
      paloaltonetworks.panos.panos_commit:
        provider: "{{ panos_provider }}"