---

- name: Firewalls Palo Alto remediation
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  vars:
    payload: "{{ ansible_eda.event.payload }}"
  tasks:
    - name: REMEDIATION - DEBUG EVENT
      debug:
        var: ansible_eda.event

    - name: Remediation - RESTORE DELETED RULES
      include_tasks: rule_main.yml
      when:
        - payload.admin == "adminmanual"
        - payload.cmd == "delete"
        - payload.result == "Succeeded"
        - '"rulebase security rules" in payload.path'

    - name: REMEDIATION - DELETE ADDED RULES
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ panos_provider }}'
        state: absent
        rule_name: "{{ payload.path | regex_search('.*rulebase security rules  (.*)','\\1') | first}}"
      when:
        - payload.admin == "adminmanual"
        - payload.cmd == "set"
        - payload.result == "Succeeded"
        - '"rulebase security rules" in payload.path'
