---

- name: Firewalls Palo Alto setup
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: COMPLIANCE - SET EVENT VAR
      set_fact:
        payload: "{{ ansible_eda.event.payload }}"

    - name: COMPLIANCE - GET INFO ON ADDED RULES
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ panos_provider }}'
        rule_name: "{{ payload.path | regex_search('.*rulebase security rules  (.*)','\\1') | first}}"
        state: gathered
      register: _rules_result

    - name: COMPLIANCE - POLICY MANUAL CHANGE
      block:
        - name: COMPLIANCE - SET manual TAG
          set_fact:
            tag_name_list: "{{ _rules_result.gathered.tag_name | default([], true) }}"
            tag_name: ['manual']

        - name: COMPLIANCE - ADD TAG TO THE LIST
          set_fact: 
            tag_name_list: "{{ tag_name_list + tag_name }}"
          when: '"manual" not in tag_name_list'

        - name: MAKE SURE manual TAG EXISTS
          paloaltonetworks.panos.panos_tag_object:
            provider: "{{ panos_provider }}"
            name: 'manual'
            color: 'red'
            comments: 'Manually created rule'

        - name: COMPLIANCE - ADD manual TAG TO ADDED RULES
          paloaltonetworks.panos.panos_security_rule:
            provider: "{{ panos_provider }}"
            rule_name: "{{ _rules_result.gathered.rule_name }}"
            description: "{{ _rules_result.gathered.description }}"
            source_zone: "{{ _rules_result.gathered.source_zone }}"
            destination_zone: "{{ _rules_result.gathered.destination_zone }}"
            source_ip: "{{ _rules_result.gathered.source_ip }}"
            destination_ip: "{{ _rules_result.gathered.destination_ip }}"
            category: "{{ _rules_result.gathered.category }}"
            application: "{{ _rules_result.gathered.application }}"
            service: "{{ _rules_result.gathered.service }}"
            action: "{{ _rules_result.gathered.action }}"
            tag_name: "{{ tag_name_list }}"
            state: replaced
            commit: "False"
      when:
        - payload.admin == "adminmanual"

    - name: COMPLIANCE - POLICY ANSIBLE CHANGE
      block:
        - name: COMPLIANCE - SET ansible TAG
          set_fact:
            tag_name_list: "{{ _rules_result.gathered.tag_name | default([], true) }}"
            tag_name: ['ansible']
        - name: COMPLIANCE - ADD TAG TO THE LIST

          set_fact: 
            tag_name_list: "{{ tag_name_list + tag_name }}"
          when: '"ansible" not in tag_name_list'

        - name: MAKE SURE ansible TAG EXISTS
          paloaltonetworks.panos.panos_tag_object:
            provider: "{{ panos_provider }}"
            name: 'ansible'
            color: 'red'
            comments: 'Ansible created rule'

        - name: COMPLIANCE - ADD ansible TAG TO ADDED RULES
          paloaltonetworks.panos.panos_security_rule:
            provider: "{{ panos_provider }}"
            rule_name: "{{ _rules_result.gathered.rule_name }}"
            description: "{{ _rules_result.gathered.description }}"
            source_zone: "{{ _rules_result.gathered.source_zone }}"
            destination_zone: "{{ _rules_result.gathered.destination_zone }}"
            source_ip: "{{ _rules_result.gathered.source_ip }}"
            destination_ip: "{{ _rules_result.gathered.destination_ip }}"
            category: "{{ _rules_result.gathered.category }}"
            application: "{{ _rules_result.gathered.application }}"
            service: "{{ _rules_result.gathered.service }}"
            action: "{{ _rules_result.gathered.action }}"
            tag_name: "{{ tag_name_list }}"
            state: replaced
            commit: "False"
      when:
        - payload.admin == "admin"

