---

- name: Firewalls Palo Alto setup
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: Debug all
      debug:
        var: ansible_eda.event

    - name: Debug
      include_tasks:
        - rule_main.yml
      # when:
      #   - ansible_eda.event.payload.admin == "adminmanual"
      #   - ansible_eda.event.payload.cmd == "delete"
      #   - ansible_eda.event.payload.result == "Succeeded"
      #   - '"rulebase security rules" in ansible_eda.event.payload.path'

