---

- name: Firewalls Palo Alto setup
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  vars:
    payload: "{{ ansible_eda.event.payload }}"
  tasks:
    - name: COMPLIANCE - DEBUG EVENT
      debug:
        var: ansible_eda.event

    - name: COMPLIANCE - CHECK TAG ON ADDED RULES
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ panos_provider }}'
        rule_name: "{{ payload.path | regex_search('.*rulebase security rules  (.*)','\\1') | first}}"
        state: gathered
      when:
        - payload.admin == "adminmanual"
        - payload.cmd == "set"
        - payload.result == "Succeeded"
        - '"rulebase security rules" in payload.path'
      register: _rules_result

    - name: Debug rules before
      debug:
        var: _rules_result

#        tag_name: "{{ my_strings + [ 'manual' ] }}"
#        - '"manual" not in _rules_result.rule_details.tag_name'


    - name: COMPLIANCE - ADD TAG TO ADDED RULES
      paloaltonetworks.panos.panos_security_rule:
        #provider: '{{ panos_provider }}'
        #state: present
        "{{ _rules_result.gathered }}"

