---

- name: Firewalls Palo Alto setup
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: Remediation - Debug EDA Event
      debug:
        var: ansible_eda.event

    - name: Remediation - restore deleted rules
      include_tasks: rule_main.yml
      when:
        - ansible_eda.event.payload.admin == "adminmanual"
        - ansible_eda.event.payload.cmd == "delete"
        - ansible_eda.event.payload.result == "Succeeded"
        - '"rulebase security rules" in ansible_eda.event.payload.path'

    - name: Gather facts from PanOS
      paloaltonetworks.panos.panos_facts:
        provider: "{{ panos_provider }}"
        gather_subset: 
          - "all" # all, system, session, interfaces, ha, routing, vr, vsys and config
      register: _panos_facts

    - name: Remediation - delete added rules
      # paloaltonetworks.panos.panos_security_rule:
      #   provider: '{{ panos_provider }}'
      #   state: absent
      #   rule_name: 'Rule X'
      debug: 
        msg: "{{ ansible_eda.event.payload.path | regex_search('rulebase security rules  .*')}}"
      when:
        - ansible_eda.event.payload.admin == "adminmanual"
        - ansible_eda.event.payload.cmd == "set"
        - ansible_eda.event.payload.result == "Succeeded"
        - '"rulebase security rules" in ansible_eda.event.payload.path'
