---

- name: Firewalls Palo Alto setup
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  vars:
    payload: "{{ ansible_eda.event.payload }}"
  tasks:
    - name: Remediation - Debug EDA Event
      debug:
        var: ansible_eda.event

    - name: Remediation - restore deleted rules
      include_tasks: rule_main.yml
      when:
        - payload.admin == "adminmanual"
        - payload.cmd == "delete"
        - payload.result == "Succeeded"
        - '"rulebase security rules" in payload.path'

    - name: Gather facts from PanOS
      paloaltonetworks.panos.panos_facts:
        provider: "{{ panos_provider }}"
        gather_subset: 
          - "all" # all, system, session, interfaces, ha, routing, vr, vsys and config
      register: _panos_facts

    - name: Remediation - delete added rules
      # paloaltonetworks.panos.panos_security_rule:
      #   provider: '{{ panos_provider }}'
      #   state: absent
      #   rule_name: 'Rule X'
      debug: 
        msg: "{{ payload.path | regex_search('.*rulebase security rules  (.*)','\\1') | first}}"
      when:
        - payload.admin == "adminmanual"
        - payload.cmd == "set"
        - payload.result == "Succeeded"
        - '"rulebase security rules" in payload.path'
