---

# PANOS SETUP
# Login to the device with the default username and password (admin/admin). 
# It may take some time until login works!
# When asked, set new password as follows:
#   admin/Cisco123
# Enter configuration mode
#   admin@fw> configure
# Change the system setting to static (DHCP is enabled by default) 
#   admin@fw# set deviceconfig system type static
# Use the following command to set the IP address of the management interface:
#   admin@fw# set deviceconfig system ip-address 172.16.2.211 netmask 255.255.248.0 default-gateway 172.16.1.1 dns-setting servers primary 8.8.8.8
# Commit the changes using the command
#   admin@fw# commit
# Exit configuration mode by using the command exit and then confirm the configurations by running the command show interface management within configuration mode
# admin@fw> show interface management
# admin@fw> show system info
#
# DEMO
# RUN panos_setup
# START EDA Rule activation
# add/delete policy rules: they will remain unchanged

- name: Firewalls Palo Alto setup
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:

    # set shared log-settings config match-list "Config Logs" filter "All Logs" send-http {{ profile_name }}
    # - name: Forward Config Logs to EDA source
    #   paloaltonetworks.panos.panos_type_cmd:
    #     provider: '{{ panos_provider }}'
    #     cmd: delete  # default
    #     xpath: "/config/shared/log-settings/config/match-list"
    #     element: |
    #       <entry name="{{ config_log_name }}">
    #         <send-http>
    #           <member>{{ profile_name }}</member>
    #         </send-http>
    #         <filter>{{ log_filter }}</filter>
    #       </entry>
    #     state: absent

    - name: Delete log forwarding profile match list
      paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
        provider: '{{ panos_provider }}'
        log_forwarding_profile: '{{ forwarding_profile_name }}'
        name: '{{ forwarding_profile_name_match_list }}'
        #log_type: traffic  # default
        filter: '{{ log_filter }}'
        http_profiles: ['{{ profile_name }}']
        state: absent

    # Log Forwarding Profile
    - name: Delete log forwarding profile
      paloaltonetworks.panos.panos_log_forwarding_profile:
        provider: '{{ panos_provider }}'
        name: '{{ forwarding_profile_name }}'
        state: absent

    # HTTP Server Profile
    # https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/config-log-fields 
    - name: Delete a HTTP Server Profile for Config Logs
      paloaltonetworks.panos.panos_http_profile:
        provider: "{{ panos_provider }}"
        name: "{{ profile_name }}"
        config_name: "{{ config_profile_name }}"
        config_uri_format: '/test'
        config_payload: >
          {
              "receive_time": "$receive_time",
              "device_name": "$device_name",
              "serial": "$serial",
              "host": "$host",
              "seqno": "$seqno",
              "type": "$type",
              "dg_id": "$dg_id",
              "type": "$type",
              "subtype": "$subtype",
              "vsys": "$vsys",
              "vsys_name": "$vsys_name",
              "admin": "$admin",
              "client": "$client",
              "cmd": "$cmd",
              "path": "$path",
              "result": "$result",
              "comment": "$comment",
              "before_change_detail": "$before-change-detail",
              "after_change_detail": "$after-change-detail"
          }
        state: absent

    - name: Delete HTTP server
      paloaltonetworks.panos.panos_http_server:
        provider: '{{ panos_provider }}'
        http_profile: '{{ profile_name }}'
        name: '{{ http_server_name }}'
        address: "{{ http_address }}"
        protocol: "{{ http_protocol }}"
        http_method: "{{ http_method }}"
        http_port: "{{ http_port }}"
        state: absent

    - name: Delete admin user for manual changes
      paloaltonetworks.panos.panos_administrator:
        provider: '{{ panos_provider }}'
        admin_username: '{{ admin_username }}'
        admin_password: '{{ admin_password }}'
        superuser: true
        state: absent

    - name: Commit configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ panos_provider }}"