---

- name: Firewalls Palo Alto setup
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: Gather facts from PanOS
      paloaltonetworks.panos.panos_facts:
        provider: "{{ panos_provider }}"
        gather_subset: 
          - "all" # all, system, session, interfaces, ha, routing, vr, vsys and config
      register: _panos_facts

    - name: Debug all
      debug:
        var: _panos_facts

    # HTTP Server Profile
    - name: Create a HTTP Server Profile for Config Logs
      paloaltonetworks.panos.panos_http_profile:
        provider: "{{ panos_provider }}"
        name: "{{ profile_name }}"
        config_name: 'auth-logs-to-eda'
        #decryption_uri_format: 'https://test'
        config_uri_format: '/test'
        config_payload: >
          {
              "category": "network",
              "details": {
                  "action": "$action",
                  "app": "$app",
                  "cn": "$cn",
                  "dst": "$dst",
                  "device_name": "$device_name",
                  "error": "$error",
                  "issuer_cn": "$issuer_cn",
                  "root_cn": "$root_cn",
                  "root_status": "$root_status",
                  "sni": "$sni",
                  "src": "$src",
                  "srcuser": "$srcuser"
              },
              "receive_time": "$receive_time",
              "rule": "$rule",
              "rule_uuid": "$rule_uuid",
              "serial": "$serial",
              "sessionid": "$sessionid",
              "severity": "informational",
              "type": "config"
          }
    - name: Create HTTP server
      paloaltonetworks.panos.panos_http_server:
        provider: '{{ panos_provider }}'
        http_profile: '{{ profile_name }}'
        name: 'my-EDA-server'
        address: "{{ httpd_address }}"
        protocol: HTTP
        http_method: 'POST'
        http_port: 5000

    - name: Add a HTTP header to HTTP Server Profile
      paloaltonetworks.panos.panos_http_profile_header:
        provider: '{{ panos_provider }}'
        http_profile: '{{ profile_name }}'
        log_type: 'config'
        header: 'Content-Type'
        value: 'application/json'

    - name: Add a param to the config log type
      paloaltonetworks.panos.panos_http_profile_param:
        provider: '{{ panos_provider }}'
        http_profile: '{{ profile_name }}'
        log_type: 'config'
        param: 'serial'
        value: '$serial'

    # Log Forwarding Profile
    - name: Create log forwarding profile
      paloaltonetworks.panos.panos_log_forwarding_profile:
        provider: '{{ panos_provider }}'
        name: 'default'
        enhanced_logging: true

    - name: Create log forwarding profile match list
      paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
        provider: '{{ panos_provider }}'
        log_forwarding_profile: 'default'
        name: 'default'
        #log_type: config
        #filter: '( err_index neq None ) and ( proxy_type eq Forward )'
        #filter: '( user eq admin ) or ( user neq admin )'
        filter: '(true eq true)'
        http_profiles: ['{{ profile_name }}']
