---

- name: Firewalls Palo Alto rules creation
  hosts: panos
  connection: local
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: Create Rules
      include_tasks: rule_main.yml
