---
- name: "Receive logs sourced from HTTP Server Profile in PAN-OS (auth events)"
  hosts: "localhost"
  # Source auth
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000
        #type: config
  # Filter config logs
  rules:
    - name: "Troubleshoot Config Logs"
      condition: true == true
      #condition: event.payload.type == "CONFIG"
      # Remediation Template
      actions:
        - print_event:
            pretty: true
        - debug: 
            var: event.payload
        - run_job_template:
            organization: "Default"
            name: "EDA Paloalto: config remediation"
            job_args:
              extra_vars:
                payload: "{{ event.payload }}"
