---
- name: "Receive logs sourced from HTTP Server Profile in PAN-OS (auth events)"
  hosts: "localhost"
  # Source auth
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000
        #type: decryption
        type: config
  # Filter decryption logs
  rules:
    - name: "Debug"
      condition: true == true
      # Remediation Template
      action:
        print_event:
          pretty: true
    - name: "Troubleshoot Decryption Logs"
      condition: event.meta.log_type == "decryption"
      # Remediation Template
      action:
        run_template:
          name: "EDA Paloalto: decryption remediation"