---
- name: "Receive logs sourced from HTTP Server Profile in PAN-OS (config events)"
  hosts: "localhost"
  # Source config
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000
        #type: config
  # Rule config logs
  rules:
    - name: "Handle Config Logs"
      condition: event.payload.type == "CONFIG"
      # Remediation Template
      actions:
        - print_event:
            pretty: true
        - debug: 
            var: event.payload.type
        - run_job_template:
            organization: "Default"
            name: "EDA Paloalto: config remediation"
            # job_args:
            #   extra_vars:
            #     payload: "{{ event.payload }}"
