---
- name: "Receive logs sourced from HTTP Server Profile in PAN-OS (config events)"
  hosts: "localhost"
  # Source config
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000
        #type: config
  # Rule config logs
  rules:
    - name: "Handle Config Logs"
      condition:
        all:
         - event.payload.type == "CONFIG"
         - event.payload.cmd == "set"
         - event.payload.result == "Succeeded"
         #- '"rulebase security rules" in event.payload.path'
      actions:
        # Debug
        # - debug: 
        #     var: event.payload.type
        - print_event:
            pretty: true
        # Config tag compliance
        - run_job_template:
            organization: "Default"
            name: "EDA Paloalto: config compliance tag"
        # Remediation Template
        # - run_job_template:
        #     organization: "Default"
        #     name: "EDA Paloalto: config remediation"
