---
- name: "Receive logs sourced from HTTP Server Profile in PAN-OS (config events)"
  hosts: "localhost"
  # Source PanOS config
  sources:
    - paloaltonetworks.panos.logs:
        host: 0.0.0.0
        port: 5000
        #type: config
  # Rule config logs
  rules:
    - name: "Handle Config Logs - Compliance "
      condition: event.payload.type == "CONFIG" and event.payload.cmd == "set" and event.payload.result == "Succeeded" and event.payload.path is search ("rulebase security rules")
      actions:
        # Debug
        # - debug: 
        #     var: event.payload
        - print_event:
            pretty: true
        # Config tag compliance
        - run_job_template:
            organization: "Default"
            name: "EDA Paloalto: config compliance tag"
        # Config log compliance
        # - run_job_template:
        #     organization: "Default"
        #     name: "EDA Paloalto: config compliance log"
        # Remediation Template
        # - run_job_template:
        #     organization: "Default"
        #     name: "EDA Paloalto: config remediation"
